

const serompe = () =>{
    return 3 + z
}

try{
    serompe()
} catch(err) {
    console.error(err)
}
